### ISSUE TITLE
datapoints

### ISSUE THREAD

**Issue by wwang72** [GridProtectionAlliance/openHistorian-grafana#1]
Hi, I configured the grafana plugin and i was able to read partial datapoints. Specifically, I can only read the *:DF points but actually i was trying to display the frequencies which end with *:F. Is there any specific configuration?

**Comment by ritchiecarroll** [comment]
Try `FILTER ActiveMeasurements WHERE SignalReference LIKE '%-FQ'`

**Comment by ritchiecarroll** [comment]
Or you can try `FILTER TOP 10 ActiveMeasurements WHERE SignalType = 'FREQ'`

**Comment by wwang72** [comment]
Thanks for the help. I was able to configure the visualization on grafana referring to your comments.
